---

- name: "Create Github deployment"
  uri:
    url: "{{ wimpy_github_deployments_api }}"
    method: POST
    headers:
      Authorization: "Token {{ wimpy_github_token }}"
      Content-Type: "application/json"
    body:
      ref: "{{ wimpy_release_version }}"
      environment: "{{ wimpy_deployment_environment }}"
      description: "Deployment by Wimpy"
    status_code: 201
    body_format: json
  register: wimpy_github_deployment_out
  ignore_errors: yes
  when:
    - wimpy_application_github_repository != ''
    - wimpy_github_token is defined
