---

- include: find_latest_ami.yml
  when: wimpy_aws_ami_id is undefined

- include: find_previous_cloudformation.yml

- include: create_github_deployment.yml

- include: update_github_deployment.yml wimpy_deployment_status="pending" wimpy_deployment_description="Deployment started"

- include: create_launchconfiguration.yml

- include: launch_cloudformation.yml

- include: remove_cloudformation.yml
  with_items: "{{ wimpy_aws_autoscaling_previous.results | default([]) }}"

- include: clean_old_launch_configurations.yml

- include: update_github_deployment.yml wimpy_deployment_status="success" wimpy_deployment_description="Deployment finished successfully"
