---

- name: "Checking that required variables are set"
  fail: msg="{{ item }} is a required variable. Set it in your playbook file or pass it as extra var"
  when: not {{ item }} is defined
  with_items:
    - wimpy_project_name
    - wimpy_docker_image_name
    - wimpy_release_version
    - wimpy_deployment_environment
    - wimpy_aws_vpc_id
    - wimpy_aws_hosted_zone_name
    - wimpy_vpc_subnets
    - wimpy_aws_elb_security_groups
    - wimpy_aws_lc_security_groups

- name: "Check that project name contain only valid characters"
  fail: msg="Project name must have a maximum of 24 characters, must contain only alphanumeric characters or hyphens, and cannot begin or end with a hyphen."
  when: (wimpy_project_name | length > 24) or
        (wimpy_project_name | regex_findall("[^a-zA-Z0-9-]") | length > 0) or
        (wimpy_project_name | regex_findall("(^-)") | length > 0) or
        (wimpy_project_name | regex_findall("(-$)") | length > 0)

- include: "{{ wimpy_before_deploy_tasks_file | default('empty.yml') }}"
- include: deploy.yml
- include: "{{ wimpy_after_deploy_tasks_file | default('empty.yml') }}"
